theme: jekyll-theme-minimal
title: Kareem Elmetwally
description: Senior Software Engineer

email: kareem.hossam1996@gmail.com
phone: +201095004184
linkedin: https://www.linkedin.com/in/kareemhossam/
github: https://github.com/kareemhossam